import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Poemas",
  description: "Generated by RapsodAz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        <header className="bg-white shadow-sm">
          <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center h-16">
              <h1 className="text-2xl font-bold text-gray-900 font-pacifico mr-8">Poemas</h1>
              <div className="flex space-x-4 ml-auto">
                <a href="/" className="text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-b-2 hover:border-blue-500">
                  Home
                </a>
                <a href="/poemas" className="text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-b-2 hover:border-blue-500">
                  Poemas
                </a>
              </div>
            </div>
          </nav>
        </header>
        <main className="min-h-screen">
          {children}
        </main>
        <footer className="w-full mt-10 py-6 bg-gray-100 text-center text-gray-500 text-sm border-t">
          © {new Date().getFullYear()} All rights reserved. RapsodAz
        </footer>
      </body>
    </html>
  );
}
